fix: multibyte line trucation
Nukesor/comfy-table pull request #162
Opened 2024-12-14 22:16 UTC by yossizahn

In some cases of cell content truncation (i.e. when the last line had to be truncated to add ellipses), the library would throw an error if the content contained multi-byte characters
See the added test case and note that it previously failed

2024-12-14 22:17 UTC, yossizahn commented
I took the lazy path of using the already existing function - `split_long_word`
Please feel free to edit my code in any way

2024-12-14 22:24 UTC, yossizahn commented
Note: While I was at it, I fixed an incorrect `>=` to `>`

2024-12-15 16:26 UTC, Nukesor requested changes
Neat! Good fix.

`split_long_word` does exactly what you want here. However, in contrast to the previous usage, you're not only splitting words but a string that might contain delimiters.

So if that's ok for you, it would be awesome if you could add a new commit in which you rename `split_long_word` to `split_string` and adjust the docstring accordingly. Otherwise I'll do that myself once this is merged :).

2024-12-15 18:57 UTC, Nukesor commented
It's kinda funny that the exact same lines of code have been touched in https://github.com/Nukesor/comfy-table/pull/163, which has been opened at around the same time as your MR. Crazy coincidence.

Anyway, since that one got merged more quickly, please do a quick rebase on `main` :) Thanks!

2025-02-02 19:34 UTC, Nukesor commented
Superseded by #167 

Thanks for the contribution anyhow, much appreciated :)

2025-02-02 19:34 UTC, closed without merging

2025-02-02 19:37 UTC, yossizahn commented
oopss... sorry for not following up, happy that someone else took the initiative

2025-02-02 21:47 UTC, Nukesor commented
Don't worry :D  
Another issue with ZWJ UTF-8 sequences came up at the same location and this needed a different approach anyhow.