handle ansi style in cell content
Nukesor/comfy-table pull request #93
Opened 2022-10-07 01:54 UTC by blueForestIcarus

intends to supersede #77
would close #91

2022-10-07 20:13 UTC, blueForestIcarus commented
@Nukesor  could you approve the CI workflow?

2022-10-08 11:14 UTC, Nukesor commented
@blueForestIcarus You can also test the CI on your fork by enabling Actions over there :)

2022-10-10 23:19 UTC, blueForestIcarus commented
@Nukesor What do you want the logic to be when the tty feature is not enabled? 
Currently I am using crossterm to identify the reset ansi code, but it looking at the crossterm source it appears to be constant.

2022-10-11 22:31 UTC, Nukesor commented
No need to setup codecov :)
As long as the other Actions succeed, you should be good to go.

Regarding the `tty` question, did you introduce any new libraries that contain `unsafe` code? If so, this could be a problem, as people rely on the current dependency tree to be fully safe and non-panicable if `tty` is disabled.

Otherwise, I don't see a big problem with including it in the default feature set.

Did you try the `build_large_tables` benchmark? If the new logic significantly increases the runtime of this benchmark, we should probably think about hiding this logic behind a feature flag (if possible).

2022-10-11 22:44 UTC, blueForestIcarus commented
Looks like console has a few unsafe blocks, but its all in term support and nothing I am using touches it.

2022-10-11 22:52 UTC, blueForestIcarus commented
```

     Running benches/build_large_table.rs (target/release/deps/build_large_table-81383246e255f825)
Huge table              time:   [18.715 ms 18.734 ms 18.755 ms]
                        change: [+24.626% +25.179% +25.712%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high mild

     Running benches/build_tables.rs (target/release/deps/build_tables-b79d9b1e4fa9749e)
Readme table            time:   [27.808 µs 27.830 µs 27.856 µs]
                        change: [+22.215% +22.616% +23.027%] (p = 0.00 < 0.05)
                        Performance has regressed.

Big table               time:   [454.56 µs 455.41 µs 456.49 µs]
                        change: [+8.5173% +8.9623% +9.3673%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 19 outliers among 100 measurements (19.00%)
  7 (7.00%) high mild
  12 (12.00%) high severe
```

2022-10-19 20:57 UTC, blueForestIcarus commented
@Nukesor let me know if that bench result is acceptable or if you want to make a feature flag.

2022-10-19 21:28 UTC, Nukesor commented
Sorry for being so slow to respond :sweat: 

I'm currently in the middle of a job transition and really don't have a lot of time to work on my open source projects.
I'll try to get to it as soon as possible :)

2022-11-11 22:22 UTC, Nukesor commented
A ~22%  performance regression for a feature that isn't being used by many users isn't that nice.

I would definitely opt to hide this behind a feature flag!
That way, we can also mark this as experimental and prevent any backward compatibility breakages.

In general, this doesn't look too bad, but it definitely needs a lot of tests :D

2022-11-11 22:22 UTC, Nukesor requested changes

2022-11-11 22:22 UTC, Nukesor commented on src/utils/formatting/content_split.rs
The current logic allows splits on arbitrary characters, including characters that could be contained inside of ansi escape codes.
We would have to somehow ensure that this won't break

2022-11-11 22:22 UTC, Nukesor commented on src/utils/formatting/content_split.rs
> +        } else {
Early `break` for better readability

2022-11-11 22:22 UTC, Nukesor commented on src/utils/formatting/content_split.rs
> +    let mut tail = String::with_capacity(word.len());
Please write proper inline documentation on what this algorithm does.
It's by no means trivial and really hard to read/understand right now.

Try to chunk the algorithm into logical blocks and explain what each block is doing in a sentence or two.

Also, please write docs on what these variables are for.

2022-11-11 22:22 UTC, Nukesor commented on src/utils/formatting/content_split.rs
> +            head.truncate(last_txt); // cut off dangling escape codes since they should have no effect
Comments above code lines

2022-11-11 22:22 UTC, Nukesor commented on Cargo.toml
> +console = "0.15.1"
`console` has a `unicode-width` feature flag.

Without this, multi-character unicode symbols won't be detected as such.

2022-11-11 22:26 UTC, Nukesor commented on src/utils/formatting/content_split.rs
> +    let mut last_txt = 0;
Let's stick with `text`. There's no reason to worsen readability for the sake of a single character

2022-11-11 22:27 UTC, Nukesor commented on src/utils/formatting/content_split.rs
> +    for (val, is_esc) in iter.by_ref() {
`val` isn't the best name for this variable.

Isn't this a iterator over characters?

2022-11-11 22:28 UTC, Nukesor commented on src/utils/formatting/content_split.rs
> +        let len = match is_esc {
What `len`? Be more descriptive

2023-02-27 20:01 UTC, blueforesticarus commented
I think I addressed everything

2023-02-28 12:37 UTC, Nukesor commented
Nice :)

I'll review it as soon as I find some time to do so!

2023-05-26 14:39 UTC, Nukesor commented
First of all, thanks for your work and time!

I'm going to merge this soon, but there were still some open issues I wanted to address first.
Since this already took so long (due to me), I took the liberty to build upon your MR and create a second MR with a few commits on top. I didn't touch any of your commits though!

Feel free to check out my additions over here:
https://github.com/Nukesor/comfy-table/pull/108

2023-05-26 14:39 UTC, merged